### ISSUE TITLE
Black Background

### ISSUE THREAD

**Issue by RazJuan** [fusionhuh/wava#3]
Hello,

I have just installed wava and I've managed to get it to show some shapes up on the screen but for me my background is just black. I've tried changing the palette and messing around with the noise gate settings but it's still just black

If there is any information I can provide to help you figure out what I've done wrong, let me know.

Thanks

**Comment by fusionhuh** [comment]
hi there,

could you play some different audio and see if a) the shapes on screen respond (become bigger) b) if they respond in time with the audio? given that the shapes generate fine i believe it may be an issue with connecting to your sound card. also what OS are you running on?
