### ISSUE TITLE
Expose aplitude data/visualization data for external program

### ISSUE THREAD

**Issue by subashz** [fusionhuh/wava#5]
Any way to expose current played visualization data (wave amplitude/strength/ for use with the external program) I want to use those data for use with another program. It can be used for changing wallpaper, conky stats, or making my led strip react to music beats and such. I have been looking at this but could not find any resources.

**Comment by fusionhuh** [comment]
yes there is! all of wava's data output for the audio frame is contained in just a single vector, wava_out, which is initialized on line 245 of wava.cpp. the 0th index contains the overall signal amplitude, 1st and 2nd indexes are unused, and indexes 3-14 contain the amplitude of each of the 12 musical notes, from A to G#. the note amplitudes can be a little fuzzy sometimes in polyphonic signals but it is generally accurate enough. 

i will create a separate repo containing wava's core internals without the unnecessary bits soon (was planning on doing this already for future projects)

**Comment by subashz** [comment]
Something simple like wava --get_current-waves will be really helpful.and easier to implement in third-party like conky, lemonbar and such. Seems like cava had the implementation but need to go through all the hassle of manually getting current waves and defining your own filters and such. it's powerful but for simple usecase it's just too much.

**Comment by fusionhuh** [comment]
apologies for the late response, i was busy yesterday.

so essentially you're looking for something that could be run as a command from the terminal as opposed to something written in c++ code?
